# Generated by Django 3.1.4 on 2020-12-26 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('court', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='team_name',
            new_name='team',
        ),
        migrations.AddField(
            model_name='team',
            name='division',
            field=models.CharField(choices=[('ATLANTIC', 'ATLANTIC Division'), ('CENTRAL', 'CENTRAL Division'), ('SOUTHEAST', 'SOUTHEAST Division'), ('NORTHWEST', 'NORTHWEST Division'), ('PACIFIC', 'PACIFIC Division'), ('SOUTHWEST', 'SOUTHWEST Division'), ('OTHER', 'OTHER Division')], default='ZZZ', max_length=10),
        ),
    ]
