# Generated by Django 3.1.4 on 2020-12-26 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('court', '0002_auto_20201226_1505'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='division',
            new_name='division_name',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='team',
            new_name='team_name',
        ),
    ]
