# Generated by Django 3.1.4 on 2020-12-29 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('court', '0004_auto_20201226_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='division_name',
            field=models.CharField(choices=[('ATLANTIC', 'ATLANTIC Division'), ('CENTRAL', 'CENTRAL Division'), ('SOUTHEAST', 'SOUTHEAST Division'), ('NORTHWEST', 'NORTHWEST Division'), ('PACIFIC', 'PACIFIC Division'), ('SOUTHWEST', 'SOUTHWEST Division'), ('OTHER', 'OTHER Division')], default='NNN', max_length=10),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_statement', models.TextField()),
                ('choice_a', models.CharField(max_length=75)),
                ('choice_b', models.CharField(max_length=75)),
                ('choice_c', models.CharField(max_length=75)),
                ('choice_d', models.CharField(max_length=75)),
                ('answer', models.CharField(max_length=1)),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='court.team')),
            ],
        ),
    ]
