# Generated by Django 3.1.4 on 2021-01-06 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('court', '0005_auto_20201229_2235'),
    ]

    operations = [
        migrations.CreateModel(
            name='Court',
            fields=[
                ('court_id', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('current_size', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
