# Generated by Django 3.1.4 on 2021-01-13 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('court', '0007_auto_20210107_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='division_name',
            field=models.CharField(choices=[('ATLANTIC', 'ATLANTIC'), ('CENTRAL', 'CENTRAL'), ('SOUTHEAST', 'SOUTHEAST'), ('NORTHWEST', 'NORTHWEST'), ('PACIFIC', 'PACIFIC'), ('SOUTHWEST', 'SOUTHWEST'), ('OTHER', 'OTHER')], default='NNN', max_length=10),
        ),
    ]
