# Generated by Django 3.1.4 on 2021-01-14 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('court', '0009_auto_20210113_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='choice_a',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='question',
            name='choice_b',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='question',
            name='choice_c',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='question',
            name='choice_d',
            field=models.CharField(max_length=150),
        ),
    ]
